package analyze_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"testing"

	"github.com/mertcikla/tld/cmd"
	"github.com/mertcikla/tld/internal/workspace"
)

func TestAnalyzeCmd_WatchPipelineWritesYAML(t *testing.T) {
	dir := t.TempDir()
	dataDir := t.TempDir()
	cmd.MustInitWorkspace(t, dir)
	repoDir := filepath.Join(dir, "app")
	cmd.InitGitRepo(t, repoDir, "service.go", "package main\nfunc Foo() {}\nfunc Bar() {}\n")

	stdout, stderr, err := cmd.RunCmd(t, dir, "analyze", repoDir, "--data-dir", dataDir, "--embedding-provider", "none")
	if err != nil {
		t.Fatalf("analyze: %v\nstdout: %s\nstderr: %s", err, stdout, stderr)
	}
	ws, err := workspace.Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if countKind(ws, "repository") != 1 || countKind(ws, "file") != 1 || countKind(ws, "function") != 2 {
		t.Fatalf("unexpected analyzed elements: %+v", ws.Elements)
	}
	for ref, element := range ws.Elements {
		if element.Kind == "function" && len(element.Placements) == 0 {
			t.Fatalf("symbol %q (%s) has no placement", element.Name, ref)
		}
	}
}

func TestAnalyzeCmd_RuntimeArtifactsUseArchitectureView(t *testing.T) {
	dir := t.TempDir()
	dataDir := t.TempDir()
	cmd.MustInitWorkspace(t, dir)
	repoDir := filepath.Join(dir, "runtime-app")
	cmd.InitGitRepo(t, repoDir, "generated/client.go", "package generated\n\n// Code generated by protoc. DO NOT EDIT.\nfunc NoisyStub() {}\n")
	writeAnalyzeTestFile(t, repoDir, "deploy/topology.yaml", `
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha
spec:
  template:
    spec:
      containers:
      - name: app
        image: example/alpha:latest
        ports:
        - containerPort: 8080
        env:
        - name: PEER
          value: "beta:9090"
        - name: CACHE
          value: "cache:6379"
---
apiVersion: v1
kind: Service
metadata:
  name: alpha
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beta
spec:
  template:
    spec:
      containers:
      - name: app
        image: example/beta:latest
        ports:
        - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: beta
spec:
  ports:
  - port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: cache
spec:
  ports:
  - port: 6379
`)

	stdout, stderr, err := cmd.RunCmd(t, dir, "analyze", repoDir, "--data-dir", dataDir, "--embedding-provider", "none")
	if err != nil {
		t.Fatalf("analyze: %v\nstdout: %s\nstderr: %s", err, stdout, stderr)
	}
	ws, err := workspace.Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if countKind(ws, "function") != 0 || countKind(ws, "file") != 0 || countKind(ws, "folder") != 0 {
		t.Fatalf("architecture view should hide code/file noise: %+v", ws.Elements)
	}
	for _, name := range []string{"alpha", "beta", "cache", "External traffic"} {
		if refByElementName(ws, name) == "" {
			t.Fatalf("missing architecture element %q in %+v", name, ws.Elements)
		}
	}
	if !connectorByElementNames(ws, "alpha", "beta") || !connectorByElementNames(ws, "alpha", "cache") || !connectorByElementNames(ws, "External traffic", "alpha") {
		t.Fatalf("missing expected architecture connectors: %+v", ws.Connectors)
	}
	for _, connector := range ws.Connectors {
		if connector.Description == "" {
			t.Fatalf("architecture connector should include provenance/confidence: %+v", connector)
		}
	}
}

func TestAnalyzeCmd_ComposeInferenceDoesNotDependOnFolderNames(t *testing.T) {
	dir := t.TempDir()
	dataDir := t.TempDir()
	cmd.MustInitWorkspace(t, dir)
	repoDir := filepath.Join(dir, "odd-layout")
	cmd.InitGitRepo(t, repoDir, "main.go", "package main\nfunc Main() {}\n")
	writeAnalyzeTestFile(t, repoDir, "ops/runtime.yml", `
services:
  worker:
    image: example/worker
    environment:
      TARGET_URL: "http://api:8080"
  api:
    image: example/api
    ports:
    - "8080:8080"
  datastore:
    image: redis:7
`)

	stdout, stderr, err := cmd.RunCmd(t, dir, "analyze", repoDir, "--data-dir", dataDir, "--embedding-provider", "none")
	if err != nil {
		t.Fatalf("analyze: %v\nstdout: %s\nstderr: %s", err, stdout, stderr)
	}
	ws, err := workspace.Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if refByElementName(ws, "worker") == "" || refByElementName(ws, "api") == "" {
		t.Fatalf("compose services were not inferred generically: %+v", ws.Elements)
	}
	if !connectorByElementNames(ws, "worker", "api") {
		t.Fatalf("expected env endpoint connector from worker to api, got %+v", ws.Connectors)
	}
	if countKind(ws, "function") != 0 {
		t.Fatalf("architecture evidence should suppress symbol-level output, got %+v", ws.Elements)
	}
}

func TestAnalyzeCmd_PreservesManualYAML(t *testing.T) {
	dir := t.TempDir()
	dataDir := t.TempDir()
	cmd.MustInitWorkspace(t, dir)
	cmd.MustRunCmd(t, dir, "add", "Manual API", "--ref", "manual-api", "--kind", "service")
	repoDir := filepath.Join(dir, "app")
	cmd.InitGitRepo(t, repoDir, "main.go", "package main\nfunc Main() {}\n")

	if stdout, stderr, err := cmd.RunCmd(t, dir, "analyze", repoDir, "--data-dir", dataDir, "--embedding-provider", "none"); err != nil {
		t.Fatalf("analyze: %v\nstdout: %s\nstderr: %s", err, stdout, stderr)
	}
	ws, err := workspace.Load(dir)
	if err != nil {
		t.Fatal(err)
	}
	if ws.Elements["manual-api"] == nil {
		t.Fatalf("manual element was not preserved: %+v", ws.Elements)
	}
}

func TestAnalyzeCmd_DryRunDoesNotWriteYAML(t *testing.T) {
	dir := t.TempDir()
	dataDir := t.TempDir()
	cmd.MustInitWorkspace(t, dir)
	repoDir := filepath.Join(dir, "app")
	cmd.InitGitRepo(t, repoDir, "service.go", "package main\nfunc Service() {}\n")
	before, err := os.ReadFile(filepath.Join(dir, "elements.yaml"))
	if err != nil {
		t.Fatal(err)
	}

	stdout, stderr, err := cmd.RunCmd(t, dir, "analyze", repoDir, "--dry-run", "--data-dir", dataDir, "--embedding-provider", "none")
	if err != nil {
		t.Fatalf("analyze --dry-run: %v\nstdout: %s\nstderr: %s", err, stdout, stderr)
	}
	after, err := os.ReadFile(filepath.Join(dir, "elements.yaml"))
	if err != nil {
		t.Fatal(err)
	}
	if string(before) != string(after) {
		t.Fatal("elements.yaml changed during dry-run")
	}
}

func TestAnalyzeCmd_RemovedFlagsFail(t *testing.T) {
	dir := t.TempDir()
	cmd.MustInitWorkspace(t, dir)
	if _, _, err := cmd.RunCmd(t, dir, "analyze", dir, "--deep"); err == nil {
		t.Fatal("expected --deep to fail")
	}
	if _, _, err := cmd.RunCmd(t, dir, "analyze", dir, "--changed-since", "HEAD"); err == nil {
		t.Fatal("expected --changed-since to fail")
	}
}

func TestAnalyzeCmd_JSONDryRunUsesWatchDiffShape(t *testing.T) {
	dir := t.TempDir()
	dataDir := t.TempDir()
	cmd.MustInitWorkspace(t, dir)
	repoDir := filepath.Join(dir, "app")
	cmd.InitGitRepo(t, repoDir, "main.go", "package main\nfunc Main() {}\n")

	stdout, stderr, err := cmd.RunCmd(t, dir, "--format", "json", "analyze", repoDir, "--dry-run", "--data-dir", dataDir, "--embedding-provider", "none")
	if err != nil {
		t.Fatalf("analyze --format json --dry-run: %v\nstdout: %s\nstderr: %s", err, stdout, stderr)
	}
	var payload struct {
		Changed        bool             `json:"changed"`
		Scan           map[string]any   `json:"scan"`
		Representation map[string]any   `json:"representation"`
		Export         map[string]any   `json:"export"`
		Diffs          []map[string]any `json:"diffs"`
	}
	if err := json.Unmarshal([]byte(stdout), &payload); err != nil {
		t.Fatalf("decode json: %v\n%s", err, stdout)
	}
	if payload.Scan["repository_id"] == nil || payload.Representation["representation_hash"] == nil || payload.Export["elements_written"] == nil {
		t.Fatalf("unexpected payload: %+v", payload)
	}
}

func countKind(ws *workspace.Workspace, kind string) int {
	count := 0
	for _, element := range ws.Elements {
		if element.Kind == kind {
			count++
		}
	}
	return count
}

func writeAnalyzeTestFile(t *testing.T, root, name, content string) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0750); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatal(err)
	}
}

func refByElementName(ws *workspace.Workspace, name string) string {
	for ref, element := range ws.Elements {
		if element.Name == name {
			return ref
		}
	}
	return ""
}

func connectorByElementNames(ws *workspace.Workspace, sourceName, targetName string) bool {
	sourceRef := refByElementName(ws, sourceName)
	targetRef := refByElementName(ws, targetName)
	if sourceRef == "" || targetRef == "" {
		return false
	}
	for _, connector := range ws.Connectors {
		if connector.Source == sourceRef && connector.Target == targetRef {
			return true
		}
	}
	return false
}
