import type { SystemStyleObject } from '@chakra-ui/react'

export const markdownPanelBodySx: SystemStyleObject = {
  '.tld-markdown-editor': {
    '--basePageBg': 'var(--bg-canvas)',
    '--baseBase': 'var(--bg-canvas)',
    '--baseBgSubtle': 'var(--bg-panel)',
    '--baseBg': 'var(--bg-element)',
    '--baseBgHover': 'var(--bg-hover)',
    '--baseLine': 'var(--border-main)',
    '--baseBorder': 'var(--border-main)',
    '--baseText': 'var(--chakra-colors-gray-100)',
    '--baseTextMuted': 'var(--chakra-colors-gray-400)',
    '--baseTextSubtle': 'var(--chakra-colors-gray-500)',
    '--baseTextContrast': 'var(--chakra-colors-whiteAlpha-900)',
    '--accentSolid': 'var(--accent)',
    '--accentText': 'var(--accent)',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    background: 'var(--bg-canvas)',
    color: 'var(--baseText)',
    containerType: 'inline-size',
  },
  '.tld-markdown-toolbar': {
    display: 'grid',
    gridTemplateColumns: 'auto minmax(0, 1fr) auto auto',
    alignItems: 'center',
    gap: '0.5rem',
    borderBottom: '1px solid var(--chakra-colors-whiteAlpha-100)',
    background: 'var(--bg-panel)',
    backdropFilter: 'blur(16px)',
    color: 'var(--baseText)',
    paddingInline: '0.625rem',
    minHeight: '48px',
    flexShrink: 0,
    overflow: 'hidden',
  },
  '.tld-markdown-mode': {
    gridColumn: '1',
    justifySelf: 'start',
    flexShrink: 0,
    padding: '2px',
    border: '1px solid var(--chakra-colors-whiteAlpha-100)',
    borderRadius: 'var(--chakra-radii-md)',
    background: 'var(--chakra-colors-whiteAlpha-100)',
    boxShadow: 'var(--chakra-shadows-panel-sm)',
  },
  '.tld-markdown-mode button': {
    height: '28px',
    minWidth: '4.25rem',
    border: '1px solid transparent',
    borderRadius: 'var(--chakra-radii-md) !important',
    background: 'transparent',
    color: 'var(--chakra-colors-whiteAlpha-700)',
    fontSize: '0.75rem',
    fontWeight: 500,
    transition: 'all 0.2s var(--chakra-transitions-easing-pop)',
  },
  '.tld-markdown-mode button[aria-pressed="true"]': {
    background: 'var(--chakra-colors-whiteAlpha-200)',
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
    boxShadow: '0 0 15px rgba(var(--accent-rgb), 0.4)',
    fontWeight: 700,
  },
  '.tld-markdown-mode button:hover': {
    background: 'var(--chakra-colors-whiteAlpha-200)',
    color: 'var(--baseTextContrast)',
    transform: 'translateY(-1px)',
    boxShadow: 'var(--chakra-shadows-panel-hover)',
  },
  '.tld-markdown-mode button[aria-pressed="true"]:hover': {
    background: 'var(--chakra-colors-whiteAlpha-300)',
    color: 'var(--baseTextContrast)',
    boxShadow: '0 0 20px rgba(var(--accent-rgb), 0.5)',
  },
  '.tld-markdown-toolbar-center': {
    gridColumn: '3',
    justifySelf: 'end',
    minWidth: 0,
    maxWidth: '100%',
  },
  '.tld-markdown-sync-group': {
    display: 'flex',
    alignItems: 'center',
    borderRight: '1px solid var(--chakra-colors-whiteAlpha-200)',
    paddingRight: '0.65rem',
    marginRight: '0.65rem',
    maxWidth: '100%',
    minWidth: 0,
  },
  '.tld-markdown-toolbar-actions': {
    gridColumn: '4',
    justifySelf: 'end',
    flexShrink: 0,
  },
  '.tld-markdown-sync-button': {
    height: '32px',
    minWidth: '32px',
    width: '32px',
    borderRadius: 'var(--chakra-radii-full)',
    paddingInline: 0,
    transition: 'all 0.2s var(--chakra-transitions-easing-pop)',
  },
  '.tld-markdown-sync-button svg': {
    width: '13px',
    height: '13px',
  },
  '.tld-markdown-sync-button:hover': {
    background: 'var(--chakra-colors-whiteAlpha-200)',
    color: 'var(--baseTextContrast)',
    transform: 'translateY(-1px)',
    boxShadow: 'var(--chakra-shadows-panel-hover)',
  },
  '.tld-markdown-sync-button-missing': {
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
  },
  '.tld-markdown-sync-button-stale': {
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
  },
  '.tld-markdown-sync-button-synced': {
    color: 'var(--accent)',
    borderColor: 'var(--accent)',
  },
  '.tld-markdown-sync-button-checking': {
    color: 'var(--chakra-colors-whiteAlpha-700)',
    borderColor: 'var(--chakra-colors-whiteAlpha-100)',
  },
  '.tld-markdown-sync-button[data-disabled], .tld-markdown-sync-button:disabled': {
    opacity: 0.72,
    cursor: 'default',
    transform: 'none',
  },
  '.tld-markdown-sync-update': {
    height: '32px',
    minWidth: '32px',
    width: '32px',
    paddingInline: 0,
    borderRadius: 'var(--chakra-radii-full)',
    color: 'var(--accent)',
    transition: 'all 0.2s var(--chakra-transitions-easing-pop)',
  },
  '.tld-markdown-sync-update:hover': {
    background: 'var(--chakra-colors-whiteAlpha-300)',
    color: 'var(--baseTextContrast)',
    transform: 'translateY(-1px)',
    boxShadow: 'var(--chakra-shadows-panel-hover)',
  },
  '.tld-markdown-sync-update svg': {
    width: '13px',
    height: '13px',
  },
  '.tld-markdown-sync-update[data-disabled], .tld-markdown-sync-update:disabled': {
    opacity: 0.38,
    cursor: 'not-allowed',
    transform: 'none',
  },
  '.tld-markdown-toolbar-action': {
    height: '32px',
    minWidth: '34px',
    width: '34px',
    paddingInline: '0',
    border: '1px solid var(--chakra-colors-whiteAlpha-100)',
    borderRadius: 'var(--chakra-radii-md)',
    fontWeight: 600,
    background: 'var(--chakra-colors-whiteAlpha-100)',
    color: 'var(--chakra-colors-whiteAlpha-700)',
    boxShadow: 'var(--chakra-shadows-panel-sm)',
    transition: 'all 0.2s var(--chakra-transitions-easing-pop)',
  },
  '.tld-markdown-toolbar-action svg': {
    width: '15px',
    height: '15px',
  },
  '.tld-markdown-toolbar-action:hover': {
    background: 'var(--chakra-colors-whiteAlpha-200)',
    color: 'var(--baseTextContrast)',
    transform: 'translateY(-1px)',
    boxShadow: 'var(--chakra-shadows-panel-hover)',
  },
  '.tld-markdown-toolbar-action-save': {
    background: 'var(--chakra-colors-whiteAlpha-200)',
    color: 'var(--baseTextContrast)',
    boxShadow: 'var(--chakra-shadows-panel-sm)',
  },
  '.tld-markdown-toolbar-action-save:hover': {
    background: 'var(--chakra-colors-whiteAlpha-300)',
    color: 'var(--baseTextContrast)',
    boxShadow: 'var(--chakra-shadows-panel-hover)',
  },
  '.tld-markdown-toolbar-action[data-disabled], .tld-markdown-toolbar-action:disabled': {
    opacity: 0.38,
    transform: 'none',
    boxShadow: 'var(--chakra-shadows-panel-sm)',
  },
  '.tld-markdown-toolbar button:focus-visible': {
    outline: '2px solid var(--accent)',
    outlineOffset: '2px',
  },
  '.tld-markdown-workspace': {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    flex: '1 1 auto',
    minHeight: 0,
    overflow: 'hidden',
  },
  '.tld-markdown-editor--source .tld-markdown-workspace, .tld-markdown-editor--preview .tld-markdown-workspace': {
    gridTemplateColumns: 'minmax(0, 1fr)',
  },
  '.tld-markdown-source-pane, .tld-markdown-preview-pane': {
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    background: 'var(--bg-canvas)',
  },
  '.tld-markdown-source-pane': {
    borderRight: '1px solid var(--baseLine)',
  },
  '.tld-markdown-editor--source .tld-markdown-source-pane': {
    borderRight: 0,
  },
  '.tld-markdown-codemirror': {
    height: '100%',
  },
  '.tld-markdown-codemirror .cm-editor': {
    height: '100%',
    background: 'var(--bg-canvas)',
    color: 'var(--baseText)',
    fontSize: '0.86rem',
  },
  '.tld-markdown-codemirror .cm-focused': {
    outline: 'none',
  },
  '.tld-markdown-codemirror .cm-scroller': {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    lineHeight: 1.62,
  },
  '.tld-markdown-codemirror .cm-gutters': {
    background: 'var(--bg-canvas)',
    borderRight: '1px solid var(--baseLine)',
    color: 'var(--baseTextSubtle)',
  },
  '.tld-markdown-codemirror .cm-activeLine, .tld-markdown-codemirror .cm-activeLineGutter': {
    background: 'rgba(var(--accent-rgb), 0.12)',
  },
  '.tld-markdown-preview-pane': {
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  '.tld-markdown-preview': {
    minHeight: '100%',
    padding: '1.25rem 1.5rem 2rem',
    fontSize: '0.95rem',
    lineHeight: 1.75,
    color: 'var(--baseText)',
  },
  '.tld-markdown-preview p': {
    marginBottom: '1rem',
  },
  '.tld-markdown-preview h1': {
    color: 'var(--baseTextContrast)',
    fontSize: '1.75em',
    fontWeight: 700,
    marginTop: '1.5rem',
    marginBottom: '0.75rem',
    lineHeight: 1.25,
  },
  '.tld-markdown-preview h2': {
    color: 'var(--baseTextContrast)',
    fontSize: '1.4em',
    fontWeight: 700,
    marginTop: '1.4rem',
    marginBottom: '0.6rem',
    lineHeight: 1.3,
  },
  '.tld-markdown-preview h3': {
    color: 'var(--baseTextContrast)',
    fontSize: '1.2em',
    fontWeight: 650,
    marginTop: '1.3rem',
    marginBottom: '0.5rem',
    lineHeight: 1.35,
  },
  '.tld-markdown-preview h4, .tld-markdown-preview h5, .tld-markdown-preview h6': {
    color: 'var(--baseTextContrast)',
    fontWeight: 650,
    marginTop: '1.1rem',
    marginBottom: '0.4rem',
  },
  '.tld-markdown-preview a': {
    color: 'var(--accentText)',
    textDecoration: 'none',
  },
  '.tld-markdown-preview a:hover': {
    textDecoration: 'underline',
  },
  '.tld-markdown-preview img': {
    display: 'inline-block',
    maxWidth: '100%',
    height: 'auto',
    verticalAlign: 'middle',
  },
  '.tld-markdown-preview blockquote': {
    borderLeft: '4px solid rgba(var(--accent-rgb), 0.45)',
    color: 'var(--baseTextMuted)',
    paddingLeft: '1rem',
    marginInline: 0,
    marginBottom: '1rem',
  },
  '.tld-markdown-preview code': {
    background: 'var(--bg-element)',
    color: 'var(--accentText)',
    padding: '0.2rem 0.4rem',
    borderRadius: '0.25rem',
    fontSize: '0.875em',
  },
  '.tld-markdown-codeblock': {
    margin: '0.9rem 0 1.15rem',
    border: '1px solid var(--baseBorder)',
    borderRadius: '0.65rem',
    background: 'var(--bg-canvas)',
    overflow: 'hidden',
  },
  '.tld-markdown-codeblock__header': {
    minHeight: '32px',
    padding: '0.42rem 0.75rem',
    borderBottom: '1px solid var(--baseLine)',
    color: 'var(--baseTextMuted)',
    background: 'var(--bg-panel)',
    fontSize: '0.72rem',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  '.tld-markdown-codeblock__pre': {
    margin: 0,
    padding: '0.9rem',
    overflowX: 'auto',
  },
  '.tld-markdown-codeblock__pre code': {
    background: 'transparent',
    padding: 0,
    borderRadius: 0,
    color: 'var(--baseText)',
    fontSize: '0.84rem',
    lineHeight: 1.65,
  },
  '.tld-markdown-preview ul, .tld-markdown-preview ol': {
    paddingLeft: '1.5rem',
    marginBottom: '1rem',
  },
  '.tld-markdown-preview li': {
    marginBottom: '0.25rem',
  },
  '.tld-markdown-preview input[type="checkbox"]': {
    marginRight: '0.45rem',
    accentColor: 'var(--accent)',
  },
  '.tld-markdown-preview table': {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '1rem 0',
    overflow: 'hidden',
    borderRadius: '0.55rem',
  },
  '.tld-markdown-preview th, .tld-markdown-preview td': {
    border: '1px solid var(--baseBorder)',
    padding: '0.5rem 0.65rem',
    verticalAlign: 'top',
  },
  '.tld-markdown-preview th': {
    background: 'var(--bg-element)',
    color: 'var(--baseTextContrast)',
    fontWeight: 700,
  },
  '.tld-markdown-preview hr': {
    border: 0,
    borderTop: '1px solid var(--baseLine)',
    margin: '1.5rem 0',
  },
  '.tld-markdown-preview details': {
    border: '1px solid var(--baseBorder)',
    borderRadius: '0.55rem',
    padding: '0.7rem 0.85rem',
    marginBottom: '1rem',
    background: 'var(--bg-panel)',
  },
  '.tld-mermaid-preview': {
    margin: '0.9rem 0 1.15rem',
    border: '1px solid var(--baseBorder)',
    borderRadius: '0.65rem',
    background: 'var(--bg-canvas)',
    overflow: 'hidden',
  },
  '.tld-mermaid-preview__header': {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    minHeight: '32px',
    padding: '0.42rem 0.75rem',
    borderBottom: '1px solid var(--baseLine)',
    color: 'var(--baseTextMuted)',
    background: 'var(--bg-panel)',
    fontSize: '0.72rem',
    fontWeight: 700,
  },
  '.tld-mermaid-preview__title': {
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '.tld-mermaid-preview__metadata': {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    minWidth: 0,
    marginLeft: 'auto',
    color: 'var(--baseTextSubtle)',
    fontSize: '0.66rem',
    fontWeight: 650,
    lineHeight: 1.45,
    whiteSpace: 'nowrap',
  },
  '.tld-mermaid-preview__meta': {
    position: 'absolute',
    left: '50%',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'inline-flex',
    alignItems: 'center',
    gap: '0.32rem',
    border: '1px solid var(--chakra-colors-whiteAlpha-100)',
    borderRadius: 'var(--chakra-radii-md)',
    padding: '0.18rem 0.42rem',
    minWidth: 0,
    maxWidth: 'min(14rem, calc(100% - 11rem))',
    color: 'var(--baseTextMuted)',
    pointerEvents: 'none',
  },
  '.tld-mermaid-preview__view-icon': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    color: 'var(--accent)',
  },
  '.tld-mermaid-preview__view-name': {
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '.tld-mermaid-preview__import': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    height: '28px',
    width: '28px',
    borderRadius: 'var(--chakra-radii-md)',
    padding: 0,
    background: 'transparent',
    border: 0,
    color: 'var(--accent)',
    lineHeight: 1,
    cursor: 'pointer',
  },
  '.tld-mermaid-preview__import:hover': {
    background: 'var(--chakra-colors-whiteAlpha-200)',
  },
  '.tld-mermaid-preview__status': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    height: '28px',
    width: '28px',
    borderRadius: 'var(--chakra-radii-md)',
    padding: 0,
    background: 'transparent',
    border: 0,
    lineHeight: 1,
    cursor: 'pointer',
  },
  '.tld-mermaid-preview__status svg': {
    width: '13px',
    height: '13px',
  },
  '.tld-mermaid-preview__status:hover': {
    background: 'var(--chakra-colors-whiteAlpha-200)',
  },
  '.tld-mermaid-preview__status[data-disabled], .tld-mermaid-preview__status:disabled': {
    cursor: 'default',
  },
  '.tld-mermaid-preview__status[data-disabled]:hover, .tld-mermaid-preview__status:disabled:hover': {
    background: 'transparent',
  },
  '.tld-mermaid-preview__status--synced': {
    color: 'var(--accent)',
  },
  '.tld-mermaid-preview__status--stale': {
    color: 'var(--accent)',
  },
  '.tld-mermaid-preview__status--other': {
    color: 'var(--accent)',
  },
  '.tld-mermaid-preview__navigate': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    height: '28px',
    width: '28px',
    borderRadius: 'var(--chakra-radii-md)',
    color: 'var(--accent)',
    padding: 0,
    lineHeight: 1,
    cursor: 'pointer',
  },
  '.tld-mermaid-preview__navigate:hover': {
    background: 'var(--chakra-colors-whiteAlpha-200)',
  },
  '.tld-mermaid-preview__body': {
    minHeight: '8rem',
    padding: '0.9rem',
    overflow: 'auto',
  },
  '.tld-mermaid-preview__body svg': {
    display: 'block',
    maxWidth: '100%',
    height: 'auto',
    margin: '0 auto',
  },
  '.tld-mermaid-preview__body svg .node rect, .tld-mermaid-preview__body svg .node polygon, .tld-mermaid-preview__body svg .node circle, .tld-mermaid-preview__body svg .node ellipse, .tld-mermaid-preview__body svg .node path': {
    fill: 'var(--bg-element) !important',
    stroke: 'var(--accent) !important',
    strokeWidth: '1.2px !important',
  },
  '.tld-mermaid-preview__body svg .nodeLabel, .tld-mermaid-preview__body svg .label, .tld-mermaid-preview__body svg .label text, .tld-mermaid-preview__body svg text': {
    color: 'var(--baseTextContrast) !important',
    fill: 'var(--baseTextContrast) !important',
  },
  '.tld-mermaid-preview__body svg .edgePath path, .tld-mermaid-preview__body svg .flowchart-link, .tld-mermaid-preview__body svg .relationshipLine': {
    stroke: 'var(--accent) !important',
    strokeWidth: '1.8px !important',
    opacity: 0.78,
  },
  '.tld-mermaid-preview__body svg marker path, .tld-mermaid-preview__body svg .arrowheadPath': {
    fill: 'var(--accent) !important',
    stroke: 'var(--accent) !important',
    opacity: 0.78,
  },
  '.tld-mermaid-preview__body svg .edgeLabel, .tld-mermaid-preview__body svg .edgeLabel p, .tld-mermaid-preview__body svg .edgeLabel rect': {
    background: 'transparent !important',
    color: 'var(--baseText) !important',
    fill: 'transparent !important',
  },
  '.tld-mermaid-preview__loading, .tld-mermaid-preview__empty': {
    display: 'flex',
    minHeight: '8rem',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--baseTextMuted)',
    fontSize: '0.84rem',
  },
  '.tld-mermaid-preview__error': {
    margin: 0,
    padding: '0.9rem',
    borderRadius: 0,
    borderTop: '1px solid color-mix(in srgb, var(--chakra-colors-red-300), transparent 78%)',
    background: 'color-mix(in srgb, var(--chakra-colors-red-900), transparent 78%)',
    color: 'var(--chakra-colors-red-200)',
    whiteSpace: 'pre-wrap',
    overflowX: 'auto',
  },
  '@container (max-width: 760px)': {
    '.tld-markdown-toolbar': {
      minHeight: '44px',
      paddingInline: '0.35rem',
      gap: '0.3rem',
    },
    '.tld-markdown-sync-button': {
      width: '32px',
      minWidth: '32px',
    },
    '.tld-markdown-workspace': {
      gridTemplateColumns: 'minmax(0, 1fr)',
      gridTemplateRows: 'minmax(0, 1fr) minmax(0, 1fr)',
    },
    '.tld-markdown-source-pane': {
      borderRight: 0,
      borderBottom: '1px solid var(--baseLine)',
    },
    '.tld-markdown-editor--source .tld-markdown-workspace, .tld-markdown-editor--preview .tld-markdown-workspace': {
      gridTemplateRows: 'minmax(0, 1fr)',
    },
    '.tld-markdown-preview': {
      padding: '1rem 1rem 1.5rem',
    },
  },
  '@container (max-width: 520px)': {
    '.tld-markdown-toolbar': {
      gridTemplateColumns: 'minmax(0, 1fr) auto',
      gridTemplateRows: 'auto auto',
      alignContent: 'center',
      rowGap: '0.35rem',
      columnGap: '0.45rem',
      minHeight: '84px',
      paddingBlock: '0.42rem',
    },
    '.tld-markdown-mode': {
      gridColumn: '1 / -1',
      justifySelf: 'center',
      maxWidth: '100%',
    },
    '.tld-markdown-mode button': {
      minWidth: '0',
      paddingInline: '0.72rem',
    },
    '.tld-markdown-toolbar-center': {
      gridColumn: '1',
      gridRow: '2',
      justifySelf: 'end',
      minWidth: 0,
    },
    '.tld-markdown-toolbar-actions': {
      gridColumn: '2',
      gridRow: '2',
      justifySelf: 'end',
    },
    '.tld-markdown-sync-button': {
      width: '32px',
      minWidth: '32px',
    },
  },
}
