import type { SystemStyleObject } from '@chakra-ui/react'

export const markdownPanelBodySx: SystemStyleObject = {
  '.tld-markdown-editor': {
    '--basePageBg': 'var(--bg-canvas)',
    '--baseBase': '#0f172a',
    '--baseBgSubtle': '#111c31',
    '--baseBg': '#152238',
    '--baseBgHover': '#1a2b46',
    '--baseLine': 'rgba(148, 163, 184, 0.18)',
    '--baseBorder': 'rgba(148, 163, 184, 0.22)',
    '--baseText': '#dbe6f5',
    '--baseTextContrast': '#f8fbff',
    '--accentSolid': '#3b82f6',
    '--accentText': '#93c5fd',
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    height: '100%',
    minHeight: 0,
    overflow: 'hidden',
    background: 'var(--bg-canvas)',
    color: '#dbe6f5',
    containerType: 'inline-size',
  },
  '.tld-markdown-toolbar': {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) auto minmax(0, 1fr)',
    alignItems: 'center',
    gap: '0.45rem',
    borderBottom: '1px solid rgba(148, 163, 184, 0.18)',
    background: 'rgba(2, 8, 23, 0.92)',
    color: '#dbe6f5',
    paddingInline: '0.5rem',
    minHeight: '46px',
    flexShrink: 0,
    overflow: 'hidden',
  },
  '.tld-markdown-mode': {
    justifySelf: 'start',
    flexShrink: 0,
  },
  '.tld-markdown-mode button': {
    height: '30px',
    borderColor: 'rgba(148, 163, 184, 0.2)',
    background: 'transparent',
    color: '#dbe6f5',
    fontSize: '0.74rem',
    fontWeight: 650,
  },
  '.tld-markdown-mode button[aria-pressed="true"]': {
    background: 'rgba(59, 130, 246, 0.24)',
    color: '#eff6ff',
  },
  '.tld-markdown-mode button:hover': {
    background: 'rgba(96, 165, 250, 0.12)',
  },
  '.tld-markdown-toolbar-center': {
    justifySelf: 'center',
    minWidth: 0,
    maxWidth: '100%',
  },
  '.tld-markdown-toolbar-actions': {
    justifySelf: 'end',
    paddingLeft: '0.5rem',
    borderLeft: '1px solid rgba(148, 163, 184, 0.12)',
    flexShrink: 0,
  },
  '.tld-markdown-sync-button': {
    height: '30px',
    maxWidth: '13.5rem',
    border: '1px solid rgba(148, 163, 184, 0.18)',
    borderRadius: '0.55rem',
    paddingInline: '0.65rem',
    background: 'rgba(15, 23, 42, 0.78)',
    color: '#dbe6f5',
    fontSize: '0.74rem',
    fontWeight: 700,
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '.tld-markdown-sync-button .chakra-button__icon': {
    marginInlineEnd: '0.42rem',
  },
  '.tld-markdown-sync-button svg': {
    width: '13px',
    height: '13px',
  },
  '.tld-markdown-sync-button:hover': {
    background: 'rgba(96, 165, 250, 0.12)',
  },
  '.tld-markdown-sync-button-missing': {
    color: '#bfdbfe',
    borderColor: 'rgba(96, 165, 250, 0.34)',
  },
  '.tld-markdown-sync-button-stale': {
    color: '#fde68a',
    borderColor: 'rgba(251, 191, 36, 0.42)',
    background: 'rgba(120, 53, 15, 0.18)',
  },
  '.tld-markdown-sync-button-synced': {
    color: '#bbf7d0',
    borderColor: 'rgba(74, 222, 128, 0.36)',
    background: 'rgba(20, 83, 45, 0.18)',
  },
  '.tld-markdown-sync-button[data-disabled], .tld-markdown-sync-button:disabled': {
    opacity: 0.72,
    cursor: 'default',
  },
  '.tld-markdown-toolbar-action': {
    height: '30px',
    minWidth: '30px',
    width: '30px',
    paddingInline: '0',
    borderRadius: '0.5rem',
    fontWeight: 600,
    background: 'transparent',
    color: '#dbe6f5',
  },
  '.tld-markdown-toolbar-action svg': {
    width: '15px',
    height: '15px',
  },
  '.tld-markdown-toolbar-action:hover': {
    background: 'rgba(96, 165, 250, 0.12)',
  },
  '.tld-markdown-toolbar-action-save': {
    background: 'rgba(59, 130, 246, 0.22)',
    color: '#eff6ff',
  },
  '.tld-markdown-toolbar-action-save:hover': {
    background: 'rgba(96, 165, 250, 0.3)',
  },
  '.tld-markdown-toolbar-action[data-disabled], .tld-markdown-toolbar-action:disabled': {
    opacity: 0.38,
    background: 'transparent',
  },
  '.tld-markdown-toolbar button:focus-visible': {
    outline: '2px solid rgba(96, 165, 250, 0.7)',
    outlineOffset: '2px',
  },
  '.tld-markdown-workspace': {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1fr) minmax(0, 1fr)',
    flex: '1 1 auto',
    minHeight: 0,
    overflow: 'hidden',
  },
  '.tld-markdown-editor--source .tld-markdown-workspace, .tld-markdown-editor--preview .tld-markdown-workspace': {
    gridTemplateColumns: 'minmax(0, 1fr)',
  },
  '.tld-markdown-source-pane, .tld-markdown-preview-pane': {
    minWidth: 0,
    minHeight: 0,
    overflow: 'hidden',
    background: 'var(--bg-canvas)',
  },
  '.tld-markdown-source-pane': {
    borderRight: '1px solid rgba(148, 163, 184, 0.14)',
  },
  '.tld-markdown-editor--source .tld-markdown-source-pane': {
    borderRight: 0,
  },
  '.tld-markdown-codemirror': {
    height: '100%',
  },
  '.tld-markdown-codemirror .cm-editor': {
    height: '100%',
    background: '#020817',
    color: '#dbe6f5',
    fontSize: '0.86rem',
  },
  '.tld-markdown-codemirror .cm-focused': {
    outline: 'none',
  },
  '.tld-markdown-codemirror .cm-scroller': {
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
    lineHeight: 1.62,
  },
  '.tld-markdown-codemirror .cm-gutters': {
    background: '#020817',
    borderRight: '1px solid rgba(148, 163, 184, 0.14)',
    color: '#64748b',
  },
  '.tld-markdown-codemirror .cm-activeLine, .tld-markdown-codemirror .cm-activeLineGutter': {
    background: 'rgba(59, 130, 246, 0.12)',
  },
  '.tld-markdown-preview-pane': {
    overflowY: 'auto',
    overflowX: 'hidden',
  },
  '.tld-markdown-preview': {
    minHeight: '100%',
    padding: '1.25rem 1.5rem 2rem',
    fontSize: '0.95rem',
    lineHeight: 1.75,
    color: '#dbe6f5',
  },
  '.tld-markdown-preview p': {
    marginBottom: '1rem',
  },
  '.tld-markdown-preview h1': {
    color: '#f8fbff',
    fontSize: '1.75em',
    fontWeight: 700,
    marginTop: '1.5rem',
    marginBottom: '0.75rem',
    lineHeight: 1.25,
  },
  '.tld-markdown-preview h2': {
    color: '#f8fbff',
    fontSize: '1.4em',
    fontWeight: 700,
    marginTop: '1.4rem',
    marginBottom: '0.6rem',
    lineHeight: 1.3,
  },
  '.tld-markdown-preview h3': {
    color: '#f8fbff',
    fontSize: '1.2em',
    fontWeight: 650,
    marginTop: '1.3rem',
    marginBottom: '0.5rem',
    lineHeight: 1.35,
  },
  '.tld-markdown-preview h4, .tld-markdown-preview h5, .tld-markdown-preview h6': {
    color: '#f8fbff',
    fontWeight: 650,
    marginTop: '1.1rem',
    marginBottom: '0.4rem',
  },
  '.tld-markdown-preview a': {
    color: '#93c5fd',
    textDecoration: 'none',
  },
  '.tld-markdown-preview a:hover': {
    textDecoration: 'underline',
  },
  '.tld-markdown-preview img': {
    display: 'inline-block',
    maxWidth: '100%',
    height: 'auto',
    verticalAlign: 'middle',
  },
  '.tld-markdown-preview blockquote': {
    borderLeft: '4px solid rgba(96, 165, 250, 0.45)',
    color: '#cbd5e1',
    paddingLeft: '1rem',
    marginInline: 0,
    marginBottom: '1rem',
  },
  '.tld-markdown-preview code': {
    background: 'rgba(30, 41, 59, 0.9)',
    color: '#bfdbfe',
    padding: '0.2rem 0.4rem',
    borderRadius: '0.25rem',
    fontSize: '0.875em',
  },
  '.tld-markdown-codeblock': {
    margin: '0.9rem 0 1.15rem',
    border: '1px solid rgba(148, 163, 184, 0.18)',
    borderRadius: '0.65rem',
    background: '#020817',
    overflow: 'hidden',
  },
  '.tld-markdown-codeblock__header': {
    minHeight: '32px',
    padding: '0.42rem 0.75rem',
    borderBottom: '1px solid rgba(148, 163, 184, 0.14)',
    color: '#94a3b8',
    background: 'rgba(15, 23, 42, 0.9)',
    fontSize: '0.72rem',
    fontWeight: 700,
    textTransform: 'uppercase',
  },
  '.tld-markdown-codeblock__pre': {
    margin: 0,
    padding: '0.9rem',
    overflowX: 'auto',
  },
  '.tld-markdown-codeblock__pre code': {
    background: 'transparent',
    padding: 0,
    borderRadius: 0,
    color: '#dbe6f5',
    fontSize: '0.84rem',
    lineHeight: 1.65,
  },
  '.tld-markdown-preview ul, .tld-markdown-preview ol': {
    paddingLeft: '1.5rem',
    marginBottom: '1rem',
  },
  '.tld-markdown-preview li': {
    marginBottom: '0.25rem',
  },
  '.tld-markdown-preview input[type="checkbox"]': {
    marginRight: '0.45rem',
    accentColor: '#3b82f6',
  },
  '.tld-markdown-preview table': {
    width: '100%',
    borderCollapse: 'collapse',
    margin: '1rem 0',
    overflow: 'hidden',
    borderRadius: '0.55rem',
  },
  '.tld-markdown-preview th, .tld-markdown-preview td': {
    border: '1px solid rgba(148, 163, 184, 0.22)',
    padding: '0.5rem 0.65rem',
    verticalAlign: 'top',
  },
  '.tld-markdown-preview th': {
    background: 'rgba(30, 41, 59, 0.74)',
    color: '#eff6ff',
    fontWeight: 700,
  },
  '.tld-markdown-preview hr': {
    border: 0,
    borderTop: '1px solid rgba(148, 163, 184, 0.2)',
    margin: '1.5rem 0',
  },
  '.tld-markdown-preview details': {
    border: '1px solid rgba(148, 163, 184, 0.18)',
    borderRadius: '0.55rem',
    padding: '0.7rem 0.85rem',
    marginBottom: '1rem',
    background: 'rgba(15, 23, 42, 0.45)',
  },
  '.tld-mermaid-preview': {
    margin: '0.9rem 0 1.15rem',
    border: '1px solid rgba(var(--accent-rgb, 99, 179, 237), 0.24)',
    borderRadius: '0.72rem',
    background: 'linear-gradient(180deg, rgba(var(--bg-main-rgb), 0.92), rgba(2, 8, 23, 0.88))',
    overflow: 'hidden',
    boxShadow: '0 16px 42px rgba(0, 0, 0, 0.22)',
  },
  '.tld-mermaid-preview--current-view': {
    borderColor: 'rgba(var(--accent-rgb, 99, 179, 237), 0.44)',
    boxShadow: '0 18px 44px rgba(0, 0, 0, 0.26), inset 0 1px 0 rgba(var(--accent-rgb, 99, 179, 237), 0.16)',
  },
  '.tld-mermaid-preview--synced': {
    borderColor: 'rgba(74, 222, 128, 0.35)',
  },
  '.tld-mermaid-preview--stale': {
    borderColor: 'rgba(250, 204, 21, 0.42)',
  },
  '.tld-mermaid-preview__header': {
    display: 'flex',
    alignItems: 'center',
    gap: '0.45rem',
    minHeight: '38px',
    padding: '0.45rem 0.75rem',
    borderBottom: '1px solid rgba(var(--accent-rgb, 99, 179, 237), 0.16)',
    background: 'linear-gradient(90deg, rgba(var(--accent-rgb, 99, 179, 237), 0.12), rgba(15, 23, 42, 0.84))',
  },
  '.tld-mermaid-preview__title': {
    color: '#eff6ff',
    fontSize: '0.78rem',
    fontWeight: 750,
    letterSpacing: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '.tld-mermaid-preview__meta': {
    color: '#94a3b8',
    fontSize: '0.72rem',
    whiteSpace: 'nowrap',
    marginLeft: 'auto',
  },
  '.tld-mermaid-preview__status': {
    border: '1px solid rgba(148, 163, 184, 0.18)',
    borderRadius: '999px',
    padding: '0.08rem 0.42rem',
    color: '#cbd5e1',
    background: 'rgba(15, 23, 42, 0.72)',
    fontSize: '0.66rem',
    fontWeight: 750,
    lineHeight: 1.45,
    whiteSpace: 'nowrap',
  },
  '.tld-mermaid-preview__status--synced': {
    color: '#bbf7d0',
    borderColor: 'rgba(74, 222, 128, 0.34)',
    background: 'rgba(20, 83, 45, 0.28)',
  },
  '.tld-mermaid-preview__status--stale': {
    color: '#fde68a',
    borderColor: 'rgba(251, 191, 36, 0.36)',
    background: 'rgba(120, 53, 15, 0.24)',
  },
  '.tld-mermaid-preview__body': {
    minHeight: '8rem',
    padding: '1rem',
    overflow: 'auto',
    background: 'radial-gradient(circle at 50% -18%, rgba(var(--accent-rgb, 99, 179, 237), 0.11), transparent 62%), var(--bg-canvas)',
  },
  '.tld-mermaid-preview__body svg': {
    display: 'block',
    maxWidth: '100%',
    height: 'auto',
    margin: '0 auto',
  },
  '.tld-mermaid-preview__body svg .node rect, .tld-mermaid-preview__body svg .node polygon, .tld-mermaid-preview__body svg .node circle, .tld-mermaid-preview__body svg .node ellipse, .tld-mermaid-preview__body svg .node path': {
    fill: 'var(--bg-element, #2d3748) !important',
    stroke: 'var(--accent, #63b3ed) !important',
    strokeWidth: '1.4px !important',
  },
  '.tld-mermaid-preview__body svg .nodeLabel, .tld-mermaid-preview__body svg .label, .tld-mermaid-preview__body svg .label text, .tld-mermaid-preview__body svg text': {
    color: '#eff6ff !important',
    fill: '#eff6ff !important',
  },
  '.tld-mermaid-preview__body svg .edgePath path, .tld-mermaid-preview__body svg .flowchart-link, .tld-mermaid-preview__body svg .relationshipLine': {
    stroke: 'var(--accent, #63b3ed) !important',
    strokeWidth: '2px !important',
    opacity: 0.86,
  },
  '.tld-mermaid-preview__body svg marker path, .tld-mermaid-preview__body svg .arrowheadPath': {
    fill: 'var(--accent, #63b3ed) !important',
    stroke: 'var(--accent, #63b3ed) !important',
  },
  '.tld-mermaid-preview__body svg .edgeLabel, .tld-mermaid-preview__body svg .edgeLabel p, .tld-mermaid-preview__body svg .edgeLabel rect': {
    background: '#171923 !important',
    color: '#dbeafe !important',
    fill: '#171923 !important',
  },
  '.tld-mermaid-preview__loading, .tld-mermaid-preview__empty': {
    display: 'flex',
    minHeight: '8rem',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#94a3b8',
    fontSize: '0.84rem',
  },
  '.tld-mermaid-preview__error': {
    margin: 0,
    padding: '0.9rem',
    borderRadius: 0,
    borderTop: '1px solid rgba(248, 113, 113, 0.22)',
    background: 'rgba(127, 29, 29, 0.22)',
    color: '#fecaca',
    whiteSpace: 'pre-wrap',
    overflowX: 'auto',
  },
  '@container (max-width: 760px)': {
    '.tld-markdown-toolbar': {
      minHeight: '44px',
      paddingInline: '0.35rem',
      gap: '0.3rem',
    },
    '.tld-markdown-sync-button': {
      maxWidth: '8.75rem',
      paddingInline: '0.5rem',
    },
    '.tld-markdown-workspace': {
      gridTemplateColumns: 'minmax(0, 1fr)',
      gridTemplateRows: 'minmax(0, 1fr) minmax(0, 1fr)',
    },
    '.tld-markdown-source-pane': {
      borderRight: 0,
      borderBottom: '1px solid rgba(148, 163, 184, 0.14)',
    },
    '.tld-markdown-editor--source .tld-markdown-workspace, .tld-markdown-editor--preview .tld-markdown-workspace': {
      gridTemplateRows: 'minmax(0, 1fr)',
    },
    '.tld-markdown-preview': {
      padding: '1rem 1rem 1.5rem',
    },
  },
}
