// Re-exports - all values have moved to constants/colors.ts.
export {
  PARENT_VIEW_COLOR as PARENT_DIAGRAM_COLOR,
  CHILD_VIEW_COLOR as CHILD_DIAGRAM_COLOR,
  PARENT_VIEW_BG as PARENT_DIAGRAM_BG,
  PARENT_VIEW_BORDER as PARENT_DIAGRAM_BORDER,
  CHILD_VIEW_BG as CHILD_DIAGRAM_BG,
  CHILD_VIEW_BORDER as CHILD_DIAGRAM_BORDER,
} from './colors'
