// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: internal/semantic/semanticpb/semantic.proto

package semanticpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityType int32

const (
	EntityType_ENTITY_TYPE_UNSPECIFIED    EntityType = 0
	EntityType_ENTITY_TYPE_SERVICE        EntityType = 1
	EntityType_ENTITY_TYPE_FUNCTION       EntityType = 2
	EntityType_ENTITY_TYPE_CLASS          EntityType = 3
	EntityType_ENTITY_TYPE_MODULE         EntityType = 4
	EntityType_ENTITY_TYPE_DATABASE       EntityType = 5
	EntityType_ENTITY_TYPE_QUEUE          EntityType = 6
	EntityType_ENTITY_TYPE_INFRASTRUCTURE EntityType = 7
	EntityType_ENTITY_TYPE_PIPELINE       EntityType = 8
	EntityType_ENTITY_TYPE_UI_COMPONENT   EntityType = 9
)

// Enum value maps for EntityType.
var (
	EntityType_name = map[int32]string{
		0: "ENTITY_TYPE_UNSPECIFIED",
		1: "ENTITY_TYPE_SERVICE",
		2: "ENTITY_TYPE_FUNCTION",
		3: "ENTITY_TYPE_CLASS",
		4: "ENTITY_TYPE_MODULE",
		5: "ENTITY_TYPE_DATABASE",
		6: "ENTITY_TYPE_QUEUE",
		7: "ENTITY_TYPE_INFRASTRUCTURE",
		8: "ENTITY_TYPE_PIPELINE",
		9: "ENTITY_TYPE_UI_COMPONENT",
	}
	EntityType_value = map[string]int32{
		"ENTITY_TYPE_UNSPECIFIED":    0,
		"ENTITY_TYPE_SERVICE":        1,
		"ENTITY_TYPE_FUNCTION":       2,
		"ENTITY_TYPE_CLASS":          3,
		"ENTITY_TYPE_MODULE":         4,
		"ENTITY_TYPE_DATABASE":       5,
		"ENTITY_TYPE_QUEUE":          6,
		"ENTITY_TYPE_INFRASTRUCTURE": 7,
		"ENTITY_TYPE_PIPELINE":       8,
		"ENTITY_TYPE_UI_COMPONENT":   9,
	}
)

func (x EntityType) Enum() *EntityType {
	p := new(EntityType)
	*p = x
	return p
}

func (x EntityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_semantic_semanticpb_semantic_proto_enumTypes[0].Descriptor()
}

func (EntityType) Type() protoreflect.EnumType {
	return &file_internal_semantic_semanticpb_semantic_proto_enumTypes[0]
}

func (x EntityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityType.Descriptor instead.
func (EntityType) EnumDescriptor() ([]byte, []int) {
	return file_internal_semantic_semanticpb_semantic_proto_rawDescGZIP(), []int{0}
}

type Property struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Property) Reset() {
	*x = Property{}
	mi := &file_internal_semantic_semanticpb_semantic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Property) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Property) ProtoMessage() {}

func (x *Property) ProtoReflect() protoreflect.Message {
	mi := &file_internal_semantic_semanticpb_semantic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Property.ProtoReflect.Descriptor instead.
func (*Property) Descriptor() ([]byte, []int) {
	return file_internal_semantic_semanticpb_semantic_proto_rawDescGZIP(), []int{0}
}

func (x *Property) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Property) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Property) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

type Relationship struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TargetUrn        string                 `protobuf:"bytes,1,opt,name=target_urn,json=targetUrn,proto3" json:"target_urn,omitempty"`
	RelationshipType string                 `protobuf:"bytes,2,opt,name=relationship_type,json=relationshipType,proto3" json:"relationship_type,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Relationship) Reset() {
	*x = Relationship{}
	mi := &file_internal_semantic_semanticpb_semantic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Relationship) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Relationship) ProtoMessage() {}

func (x *Relationship) ProtoReflect() protoreflect.Message {
	mi := &file_internal_semantic_semanticpb_semantic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Relationship.ProtoReflect.Descriptor instead.
func (*Relationship) Descriptor() ([]byte, []int) {
	return file_internal_semantic_semanticpb_semantic_proto_rawDescGZIP(), []int{1}
}

func (x *Relationship) GetTargetUrn() string {
	if x != nil {
		return x.TargetUrn
	}
	return ""
}

func (x *Relationship) GetRelationshipType() string {
	if x != nil {
		return x.RelationshipType
	}
	return ""
}

func (x *Relationship) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SystemContext struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ExecutionBoundaries []string               `protobuf:"bytes,1,rep,name=execution_boundaries,json=executionBoundaries,proto3" json:"execution_boundaries,omitempty"`
	Triggers            []string               `protobuf:"bytes,2,rep,name=triggers,proto3" json:"triggers,omitempty"`
	ExternalBindings    []string               `protobuf:"bytes,3,rep,name=external_bindings,json=externalBindings,proto3" json:"external_bindings,omitempty"`
	CustomAttributes    map[string]string      `protobuf:"bytes,4,rep,name=custom_attributes,json=customAttributes,proto3" json:"custom_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SystemContext) Reset() {
	*x = SystemContext{}
	mi := &file_internal_semantic_semanticpb_semantic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemContext) ProtoMessage() {}

func (x *SystemContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_semantic_semanticpb_semantic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemContext.ProtoReflect.Descriptor instead.
func (*SystemContext) Descriptor() ([]byte, []int) {
	return file_internal_semantic_semanticpb_semantic_proto_rawDescGZIP(), []int{2}
}

func (x *SystemContext) GetExecutionBoundaries() []string {
	if x != nil {
		return x.ExecutionBoundaries
	}
	return nil
}

func (x *SystemContext) GetTriggers() []string {
	if x != nil {
		return x.Triggers
	}
	return nil
}

func (x *SystemContext) GetExternalBindings() []string {
	if x != nil {
		return x.ExternalBindings
	}
	return nil
}

func (x *SystemContext) GetCustomAttributes() map[string]string {
	if x != nil {
		return x.CustomAttributes
	}
	return nil
}

type SymbolContext struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Urn                 string                 `protobuf:"bytes,1,opt,name=urn,proto3" json:"urn,omitempty"`
	SymbolName          string                 `protobuf:"bytes,2,opt,name=symbol_name,json=symbolName,proto3" json:"symbol_name,omitempty"`
	EntityType          EntityType             `protobuf:"varint,3,opt,name=entity_type,json=entityType,proto3,enum=semantic_embedding.EntityType" json:"entity_type,omitempty"`
	SourceLanguage      string                 `protobuf:"bytes,4,opt,name=source_language,json=sourceLanguage,proto3" json:"source_language,omitempty"`
	DomainBoundary      string                 `protobuf:"bytes,5,opt,name=domain_boundary,json=domainBoundary,proto3" json:"domain_boundary,omitempty"`
	RawSignature        string                 `protobuf:"bytes,6,opt,name=raw_signature,json=rawSignature,proto3" json:"raw_signature,omitempty"`
	NaturalLanguageDocs string                 `protobuf:"bytes,7,opt,name=natural_language_docs,json=naturalLanguageDocs,proto3" json:"natural_language_docs,omitempty"`
	Properties          []*Property            `protobuf:"bytes,8,rep,name=properties,proto3" json:"properties,omitempty"`
	Relationships       []*Relationship        `protobuf:"bytes,9,rep,name=relationships,proto3" json:"relationships,omitempty"`
	SystemContext       *SystemContext         `protobuf:"bytes,10,opt,name=system_context,json=systemContext,proto3" json:"system_context,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SymbolContext) Reset() {
	*x = SymbolContext{}
	mi := &file_internal_semantic_semanticpb_semantic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolContext) ProtoMessage() {}

func (x *SymbolContext) ProtoReflect() protoreflect.Message {
	mi := &file_internal_semantic_semanticpb_semantic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolContext.ProtoReflect.Descriptor instead.
func (*SymbolContext) Descriptor() ([]byte, []int) {
	return file_internal_semantic_semanticpb_semantic_proto_rawDescGZIP(), []int{3}
}

func (x *SymbolContext) GetUrn() string {
	if x != nil {
		return x.Urn
	}
	return ""
}

func (x *SymbolContext) GetSymbolName() string {
	if x != nil {
		return x.SymbolName
	}
	return ""
}

func (x *SymbolContext) GetEntityType() EntityType {
	if x != nil {
		return x.EntityType
	}
	return EntityType_ENTITY_TYPE_UNSPECIFIED
}

func (x *SymbolContext) GetSourceLanguage() string {
	if x != nil {
		return x.SourceLanguage
	}
	return ""
}

func (x *SymbolContext) GetDomainBoundary() string {
	if x != nil {
		return x.DomainBoundary
	}
	return ""
}

func (x *SymbolContext) GetRawSignature() string {
	if x != nil {
		return x.RawSignature
	}
	return ""
}

func (x *SymbolContext) GetNaturalLanguageDocs() string {
	if x != nil {
		return x.NaturalLanguageDocs
	}
	return ""
}

func (x *SymbolContext) GetProperties() []*Property {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *SymbolContext) GetRelationships() []*Relationship {
	if x != nil {
		return x.Relationships
	}
	return nil
}

func (x *SymbolContext) GetSystemContext() *SystemContext {
	if x != nil {
		return x.SystemContext
	}
	return nil
}

var File_internal_semantic_semanticpb_semantic_proto protoreflect.FileDescriptor

const file_internal_semantic_semanticpb_semantic_proto_rawDesc = "" +
	"\n" +
	"+internal/semantic/semanticpb/semantic.proto\x12\x12semantic_embedding\"H\n" +
	"\bProperty\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\"|\n" +
	"\fRelationship\x12\x1d\n" +
	"\n" +
	"target_urn\x18\x01 \x01(\tR\ttargetUrn\x12+\n" +
	"\x11relationship_type\x18\x02 \x01(\tR\x10relationshipType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\xb6\x02\n" +
	"\rSystemContext\x121\n" +
	"\x14execution_boundaries\x18\x01 \x03(\tR\x13executionBoundaries\x12\x1a\n" +
	"\btriggers\x18\x02 \x03(\tR\btriggers\x12+\n" +
	"\x11external_bindings\x18\x03 \x03(\tR\x10externalBindings\x12d\n" +
	"\x11custom_attributes\x18\x04 \x03(\v27.semantic_embedding.SystemContext.CustomAttributesEntryR\x10customAttributes\x1aC\n" +
	"\x15CustomAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfe\x03\n" +
	"\rSymbolContext\x12\x10\n" +
	"\x03urn\x18\x01 \x01(\tR\x03urn\x12\x1f\n" +
	"\vsymbol_name\x18\x02 \x01(\tR\n" +
	"symbolName\x12?\n" +
	"\ventity_type\x18\x03 \x01(\x0e2\x1e.semantic_embedding.EntityTypeR\n" +
	"entityType\x12'\n" +
	"\x0fsource_language\x18\x04 \x01(\tR\x0esourceLanguage\x12'\n" +
	"\x0fdomain_boundary\x18\x05 \x01(\tR\x0edomainBoundary\x12#\n" +
	"\rraw_signature\x18\x06 \x01(\tR\frawSignature\x122\n" +
	"\x15natural_language_docs\x18\a \x01(\tR\x13naturalLanguageDocs\x12<\n" +
	"\n" +
	"properties\x18\b \x03(\v2\x1c.semantic_embedding.PropertyR\n" +
	"properties\x12F\n" +
	"\rrelationships\x18\t \x03(\v2 .semantic_embedding.RelationshipR\rrelationships\x12H\n" +
	"\x0esystem_context\x18\n" +
	" \x01(\v2!.semantic_embedding.SystemContextR\rsystemContext*\x94\x02\n" +
	"\n" +
	"EntityType\x12\x1b\n" +
	"\x17ENTITY_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ENTITY_TYPE_SERVICE\x10\x01\x12\x18\n" +
	"\x14ENTITY_TYPE_FUNCTION\x10\x02\x12\x15\n" +
	"\x11ENTITY_TYPE_CLASS\x10\x03\x12\x16\n" +
	"\x12ENTITY_TYPE_MODULE\x10\x04\x12\x18\n" +
	"\x14ENTITY_TYPE_DATABASE\x10\x05\x12\x15\n" +
	"\x11ENTITY_TYPE_QUEUE\x10\x06\x12\x1e\n" +
	"\x1aENTITY_TYPE_INFRASTRUCTURE\x10\a\x12\x18\n" +
	"\x14ENTITY_TYPE_PIPELINE\x10\b\x12\x1c\n" +
	"\x18ENTITY_TYPE_UI_COMPONENT\x10\tB:Z8github.com/mertcikla/tld/v2/internal/semantic/semanticpbb\x06proto3"

var (
	file_internal_semantic_semanticpb_semantic_proto_rawDescOnce sync.Once
	file_internal_semantic_semanticpb_semantic_proto_rawDescData []byte
)

func file_internal_semantic_semanticpb_semantic_proto_rawDescGZIP() []byte {
	file_internal_semantic_semanticpb_semantic_proto_rawDescOnce.Do(func() {
		file_internal_semantic_semanticpb_semantic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_semantic_semanticpb_semantic_proto_rawDesc), len(file_internal_semantic_semanticpb_semantic_proto_rawDesc)))
	})
	return file_internal_semantic_semanticpb_semantic_proto_rawDescData
}

var file_internal_semantic_semanticpb_semantic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_semantic_semanticpb_semantic_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_semantic_semanticpb_semantic_proto_goTypes = []any{
	(EntityType)(0),       // 0: semantic_embedding.EntityType
	(*Property)(nil),      // 1: semantic_embedding.Property
	(*Relationship)(nil),  // 2: semantic_embedding.Relationship
	(*SystemContext)(nil), // 3: semantic_embedding.SystemContext
	(*SymbolContext)(nil), // 4: semantic_embedding.SymbolContext
	nil,                   // 5: semantic_embedding.SystemContext.CustomAttributesEntry
}
var file_internal_semantic_semanticpb_semantic_proto_depIdxs = []int32{
	5, // 0: semantic_embedding.SystemContext.custom_attributes:type_name -> semantic_embedding.SystemContext.CustomAttributesEntry
	0, // 1: semantic_embedding.SymbolContext.entity_type:type_name -> semantic_embedding.EntityType
	1, // 2: semantic_embedding.SymbolContext.properties:type_name -> semantic_embedding.Property
	2, // 3: semantic_embedding.SymbolContext.relationships:type_name -> semantic_embedding.Relationship
	3, // 4: semantic_embedding.SymbolContext.system_context:type_name -> semantic_embedding.SystemContext
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_internal_semantic_semanticpb_semantic_proto_init() }
func file_internal_semantic_semanticpb_semantic_proto_init() {
	if File_internal_semantic_semanticpb_semantic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_semantic_semanticpb_semantic_proto_rawDesc), len(file_internal_semantic_semanticpb_semantic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_semantic_semanticpb_semantic_proto_goTypes,
		DependencyIndexes: file_internal_semantic_semanticpb_semantic_proto_depIdxs,
		EnumInfos:         file_internal_semantic_semanticpb_semantic_proto_enumTypes,
		MessageInfos:      file_internal_semantic_semanticpb_semantic_proto_msgTypes,
	}.Build()
	File_internal_semantic_semanticpb_semantic_proto = out.File
	file_internal_semantic_semanticpb_semantic_proto_goTypes = nil
	file_internal_semantic_semanticpb_semantic_proto_depIdxs = nil
}
